exclude: (^notebooks/)
repos:
  - repo: https://github.com/pdm-project/pdm
    rev: 2.9.3 # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check
      - id: pdm-export
        # command arguments, e.g.:
        args: [ '-o', 'requirements.txt', '--without-hashes', '--prod' ]
        files: ^pdm.lock$
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        language: system
        args: [--fix, --exit-non-zero-on-fix]
        types: [ python ]
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: (^docs/)
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [ file, python ]
        exclude: (^docs/)
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [ file, python ]
        exclude: (^docs/)
