version: "3"

# You can also ask Task to include .env like files by using the dotenv: setting:
dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

# If `--` is given in the CLI, all following parameters are added to a special .CLI_ARGS variable.
# This is useful to forward arguments to another command.

tasks:

  check-config:
    desc: Check Hydra configuration
    cmds:
      - python met/train.py --cfg all --resolve {{.CLI_ARGS}}

  wandb:
    desc: Login to Weights & Biases
    cmds:
      - wandb login $WANDB_KEY

  train:
    desc: Train a model
    cmds:
      - python met/train.py {{.CLI_ARGS}}

  compare:
    desc: Compare using linear baselines
    cmds:
      - python met/compare.py {{.CLI_ARGS}}
    sources:
      - met/conf/comps.yaml
      - met/compare.py
    generates:
      - outputs/comps/adult-income.json
      - outputs/comps/cover-type.json