# These aren't directly instantiated via Hydra
# Instead, they're instantiated using a helper function
# See utils.instantiate_callbacks for implementation
model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary

progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
  refresh_rate: 5
  leave: True

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: valid-loss
  min_delta: 0.001
  patience: 10
  check_on_train_epoch_end: True

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${hydra:runtime.output_dir}/checkpoints
  monitor: valid-loss
  save_top_k: 1
  save_on_train_epoch_end: True
