name: cover-type

dataset:
  _target_: met.data.get_covtype_alt_dataset
  train: False

models:
  met-32:
    name: MET-32
    # Latest Lightning version loads checkpoints from class, not instance
    cls: met.models.met.MET
    ckpt_path: MET-32/train/2023-12-10/22-48-36/checkpoints/epoch=36-step=67192.ckpt