defaults:
  - default

eval:
  cls:
    _target_: sklearn.linear_model.LogisticRegression
    max_iter: 300
  train_data:
    _target_: met.data.get_income_dataset
    train: True
  test_data:
    _target_: met.data.get_income_dataset
    train: False