cls:
  _target_: sklearn.linear_model.LogisticRegression
  max_iter: 300
  C: 0.1
  tol: 0.001
  solver: saga
  verbose: 1
  n_jobs: 4
train_data:
  _target_: met.data.get_covtype_alt_dataset
  train: True
  subset: .25
test_data:
  _target_: met.data.get_covtype_alt_dataset
  train: False